package com.example.data.local

import com.example.data.model.HistoricalLogEntity
import com.example.data.model.NgoEntity
import com.example.data.model.VerificationStatus

object SeedData {

  fun getVerifiedNgos(): List<NgoEntity> = listOf(
    NgoEntity(
      ngoId = "ngo_bandh_foundation",
      name = "Bandh Foundation - NGO in Kolhapur",
      description = "Official hunger-relief and food donation drive organization serving surplus food to underprivileged communities across Kolhapur.",
      address = "Shop A-6, 328 E, Dabholkar Chowk, Shahupuri, Kolhapur 416003",
      city = "Kolhapur",
      state = "Maharashtra",
      pincode = "416003",
      latitude = 16.7028,
      longitude = 74.2384,
      serviceArea = "Kolhapur City & Shahupuri District",
      contactMethod = "Direct Helpline / Food Drive Desk",
      phone = "+91 83290 55881",
      email = "contact@bandhfoundation.org",
      website = "https://bandhfoundation.org",
      sourceUrl = "https://bandhfoundation.org",
      acceptsCookedFood = true,
      acceptsPackedFood = true,
      acceptsRawFood = true,
      foodAcceptanceStatus = "Accepts Cooked & Packaged Food",
      pickupAvailable = true,
      pickupAvailabilityStatus = "Pickup Available",
      pickupWindow = "Same-day volunteer pickup available",
      capacityBadge = "FOOD RESCUE PARTNER",
      verificationStatus = VerificationStatus.VERIFIED,
      lastVerifiedAt = "August 2026",
      verificationNotes = "Strong candidate — its official site lists an active Food Donation Drive and hunger-relief operations.",
      distanceKm = 1.8
    ),
    NgoEntity(
      ngoId = "ngo_mahalakshmi_annachhatra",
      name = "Shri Mahalakshmi Annachhatra Seva Trust",
      description = "Food-serving charitable trust providing daily meals to pilgrims and communities in Kolhapur.",
      address = "Shivaji Peth, A/C Ward, Kolhapur 416012",
      city = "Kolhapur",
      state = "Maharashtra",
      pincode = "416012",
      latitude = 16.6913,
      longitude = 74.2215,
      serviceArea = "Shivaji Peth & Central Kolhapur",
      contactMethod = "Trust Office",
      phone = "+91 98609 04241",
      email = "info@mahalaxmisevatrust.org",
      website = "https://mahalaxmisevatrust.org",
      sourceUrl = "https://mahalaxmisevatrust.org",
      acceptsCookedFood = true,
      acceptsPackedFood = true,
      acceptsRawFood = true,
      foodAcceptanceStatus = "Contact to Confirm",
      pickupAvailable = false,
      pickupAvailabilityStatus = "Contact to Confirm",
      pickupWindow = "Contact trust office (0231-2626377 / +91 98609 04241) to confirm drop-off or pickup",
      capacityBadge = "CONTACT TO CONFIRM",
      verificationStatus = VerificationStatus.NEEDS_REVIEW,
      lastVerifiedAt = "August 2026",
      verificationNotes = "Food-serving charitable trust; confirm whether it currently accepts external surplus-food pickups before integrating.",
      distanceKm = 2.6
    ),
    NgoEntity(
      ngoId = "ngo_neem_karoli_baba",
      name = "Neem Karoli Baba Charitable Trust",
      description = "Charitable initiative dedicated to nourishing the hungry, distributing food grains, and community welfare in Sambhaji Nagar.",
      address = "Flat No. 401, Raj Sai Apartment, Sambhaji Nagar, Kolhapur",
      city = "Kolhapur",
      state = "Maharashtra",
      pincode = "416001",
      latitude = 16.6850,
      longitude = 74.2310,
      serviceArea = "Sambhaji Nagar & South Kolhapur",
      contactMethod = "Helpline",
      phone = "+91 97630 41193",
      email = "trust@neemkarolibaba.org",
      website = "https://neemkarolibaba.org",
      sourceUrl = "https://neemkarolibaba.org",
      acceptsCookedFood = true,
      acceptsPackedFood = true,
      acceptsRawFood = true,
      foodAcceptanceStatus = "Contact to Confirm",
      pickupAvailable = false,
      pickupAvailabilityStatus = "Contact to Confirm",
      pickupWindow = "Contact trust coordinators to confirm pickup arrangements",
      capacityBadge = "CONTACT TO CONFIRM",
      verificationStatus = VerificationStatus.NEEDS_REVIEW,
      lastVerifiedAt = "August 2026",
      verificationNotes = "Its official site specifically mentions “nourishing the hungry”; confirm surplus-food collection arrangements.",
      distanceKm = 3.5
    ),
    NgoEntity(
      ngoId = "ngo_ova_kolhapur",
      name = "OVA / Bharatiya Open Volunteer Association",
      description = "Open volunteer network engaging youth in community welfare, relief distribution, and food assistance.",
      address = "Chavan-Dafale Colony, Uchgaon, Kolhapur 416005",
      city = "Kolhapur",
      state = "Maharashtra",
      pincode = "416005",
      latitude = 16.6811,
      longitude = 74.2672,
      serviceArea = "Uchgaon & Kolhapur Suburbs",
      contactMethod = "Volunteer Helpline",
      phone = "+91 80806 77811",
      email = "volunteers@ova.org.in",
      website = "https://ova.org.in",
      sourceUrl = "https://ova.org.in",
      acceptsCookedFood = false,
      acceptsPackedFood = true,
      acceptsRawFood = true,
      foodAcceptanceStatus = "Contact to Confirm",
      pickupAvailable = false,
      pickupAvailabilityStatus = "Contact to Confirm",
      pickupWindow = "Volunteer on-call coordination",
      capacityBadge = "CONTACT TO CONFIRM",
      verificationStatus = VerificationStatus.NEEDS_REVIEW,
      lastVerifiedAt = "August 2026",
      verificationNotes = "Community-support NGO; its site mentions food and welfare support, but cooked-food pickup should be confirmed.",
      distanceKm = 4.2
    ),
    NgoEntity(
      ngoId = "ngo_robin_hood_army",
      name = "Robin Hood Army",
      description = "Zero-funds volunteer organization that serves surplus food from restaurants and communities to the less fortunate.",
      address = "Block C, Connaught Place, New Delhi 110001",
      city = "New Delhi",
      state = "Delhi",
      pincode = "110001",
      latitude = 28.6304,
      longitude = 77.2177,
      serviceArea = "All major metro chapters across India (400+ cities)",
      contactMethod = "WhatsApp & Phone Dispatch",
      phone = "+91 98200 12345",
      email = "info@robinhoodarmy.com",
      website = "https://robinhoodarmy.com",
      sourceUrl = "https://robinhoodarmy.com",
      acceptsCookedFood = true,
      acceptsPackedFood = true,
      acceptsRawFood = false,
      foodAcceptanceStatus = "Accepts Cooked & Packaged Food",
      pickupAvailable = true,
      pickupAvailabilityStatus = "Pickup Available",
      pickupWindow = "2-hour window",
      capacityBadge = "HIGH DEMAND",
      verificationStatus = VerificationStatus.VERIFIED,
      lastVerifiedAt = "August 2026",
      verificationNotes = "Audited volunteer network. Cold-chain storage for cooked food.",
      distanceKm = 4.8
    ),
    NgoEntity(
      ngoId = "ngo_no_food_waste",
      name = "No Food Waste",
      description = "Mission to feed hungry stomachs by recovering untouched edible surplus food from marriages, canteens, and parties.",
      address = "42, 1st Cross, Koramangala 4th Block, Bengaluru 560034",
      city = "Bengaluru",
      state = "Karnataka",
      pincode = "560034",
      latitude = 12.9352,
      longitude = 77.6245,
      serviceArea = "South India chapters (Bengaluru, Chennai, Coimbatore, Hyderabad)",
      contactMethod = "Toll-Free Helpline & Van Dispatch",
      phone = "+91 90877 90877",
      email = "feed@nofoodwaste.org",
      website = "https://nofoodwaste.org",
      sourceUrl = "https://nofoodwaste.org",
      acceptsCookedFood = true,
      acceptsPackedFood = true,
      acceptsRawFood = true,
      foodAcceptanceStatus = "Accepts Cooked, Packaged & Raw",
      pickupAvailable = true,
      pickupAvailabilityStatus = "Pickup Available",
      pickupWindow = "Large vehicle pickup available (50kg+)",
      capacityBadge = "CAPACITY: 50KG+",
      verificationStatus = VerificationStatus.VERIFIED,
      lastVerifiedAt = "August 2026",
      verificationNotes = "Operates dedicated temperature-controlled mobile food vans.",
      distanceKm = 5.1
    ),
    NgoEntity(
      ngoId = "ngo_feeding_india",
      name = "Feeding India (Zomato)",
      description = "Non-profit dedicated to eradicating hunger and malnutrition in India through daily meal drives and emergency food relief.",
      address = "DLF Cyber City, Phase 2, Gurugram 122002",
      city = "Gurugram",
      state = "Haryana",
      pincode = "122002",
      latitude = 28.4906,
      longitude = 77.0903,
      serviceArea = "Nationwide coverage across 100+ Tier 1 & 2 cities",
      contactMethod = "Zomato Relief Logistics",
      phone = "+91 98111 88990",
      email = "contact@feedingindia.org",
      website = "https://feedingindia.org",
      sourceUrl = "https://feedingindia.org",
      acceptsCookedFood = false,
      acceptsPackedFood = true,
      acceptsRawFood = true,
      foodAcceptanceStatus = "Packaged & Raw Grains Only",
      pickupAvailable = false,
      pickupAvailabilityStatus = "Drop-off Only",
      pickupWindow = "Drop-off only (10:00 AM - 6:00 PM)",
      capacityBadge = "RAW & PACKAGED",
      verificationStatus = VerificationStatus.VERIFIED,
      lastVerifiedAt = "August 2026",
      verificationNotes = "Audited distribution centers. Special focus on raw grains and dry ration kits.",
      distanceKm = 6.2
    ),
    NgoEntity(
      ngoId = "ngo_roti_bank",
      name = "Roti Bank Foundation",
      description = "Bridging the gap between hunger and excess food with GPS-tracked emergency rescue vans.",
      address = "Lower Parel West, Mumbai 400013",
      city = "Mumbai",
      state = "Maharashtra",
      pincode = "400013",
      latitude = 18.9950,
      longitude = 72.8285,
      serviceArea = "Mumbai Metropolitan Region, Pune, Nagpur",
      contactMethod = "Helpline 86555 80001",
      phone = "+91 86555 80001",
      email = "help@rotibankfoundation.org",
      website = "https://rotibankfoundation.org",
      sourceUrl = "https://rotibankfoundation.org",
      acceptsCookedFood = true,
      acceptsPackedFood = true,
      acceptsRawFood = true,
      foodAcceptanceStatus = "Accepts Cooked, Packaged & Raw",
      pickupAvailable = true,
      pickupAvailabilityStatus = "Pickup Available",
      pickupWindow = "Same-day van dispatch within 90 mins",
      capacityBadge = "24/7 HELPLINE",
      verificationStatus = VerificationStatus.VERIFIED,
      lastVerifiedAt = "August 2026",
      verificationNotes = "Established by retired DGP. Government certified NGO.",
      distanceKm = 7.4
    ),
    NgoEntity(
      ngoId = "ngo_ifbn",
      name = "India Food Banking Network (IFBN)",
      description = "Institutional food banking system managing warehouse-level distribution of grain surplus to orphanages and old age homes.",
      address = "Qutab Institutional Area, New Delhi 110016",
      city = "New Delhi",
      state = "Delhi",
      pincode = "110016",
      latitude = 28.5375,
      longitude = 77.1856,
      serviceArea = "Delhi NCR, Kolkata, Ahmedabad, Chandigarh",
      contactMethod = "Institutional Portal",
      phone = "+91 11 4100 2233",
      email = "network@indiafoodbanking.org",
      website = "https://indiafoodbanking.org",
      sourceUrl = "https://indiafoodbanking.org",
      acceptsCookedFood = false,
      acceptsPackedFood = true,
      acceptsRawFood = true,
      foodAcceptanceStatus = "Packaged & Raw Surplus",
      pickupAvailable = true,
      pickupAvailabilityStatus = "Pickup Available",
      pickupWindow = "Scheduled warehouse pickup",
      capacityBadge = "INSTITUTIONAL",
      verificationStatus = VerificationStatus.VERIFIED,
      lastVerifiedAt = "August 2026",
      verificationNotes = "FSSAI recognized food banking initiative.",
      distanceKm = 8.8
    ),
    NgoEntity(
      ngoId = "ngo_annakshetra",
      name = "Annakshetra Trust",
      description = "Collecting surplus food from large marriages and catering events, testing quality, and serving hygienic meals.",
      address = "MI Road, Panch Batti, Jaipur 302001",
      city = "Jaipur",
      state = "Rajasthan",
      pincode = "302001",
      latitude = 26.9161,
      longitude = 75.8173,
      serviceArea = "Jaipur, Kota, Ajmer",
      contactMethod = "Event Rescue Desk",
      phone = "+91 90012 34567",
      email = "contact@annakshetra.org",
      website = "https://annakshetra.org",
      sourceUrl = "https://annakshetra.org",
      acceptsCookedFood = true,
      acceptsPackedFood = false,
      acceptsRawFood = false,
      foodAcceptanceStatus = "Contact to Confirm",
      pickupAvailable = true,
      pickupAvailabilityStatus = "Contact to Confirm",
      pickupWindow = "Evening & Night Event Pickup",
      capacityBadge = "CONTACT TO CONFIRM",
      verificationStatus = VerificationStatus.NEEDS_REVIEW,
      lastVerifiedAt = "July 2026",
      verificationNotes = "Availability must be confirmed with the organization for late night pickups.",
      distanceKm = 11.5
    )
  )

  fun getInitialHistoricalLogs(providerId: String): List<HistoricalLogEntity> = listOf(
    HistoricalLogEntity(
      providerId = providerId,
      date = "2026-08-25",
      dayOfWeek = "Monday",
      mealType = "Lunch",
      foodItems = "Rice, Dal Tadka, Paneer Butter Masala, Chapati",
      quantityPrepared = 200.0,
      quantityConsumed = 170.0,
      quantityRemaining = 30.0,
      quantityRescued = 28.0,
      quantityWasted = 2.0,
      ordersCount = 165,
      isHoliday = false,
      isWeekend = false,
      specialEvent = null,
      weatherContext = "Sunny 28°C"
    ),
    HistoricalLogEntity(
      providerId = providerId,
      date = "2026-08-26",
      dayOfWeek = "Tuesday",
      mealType = "Lunch",
      foodItems = "Jeera Rice, Chana Masala, Aloo Gobi, Roti",
      quantityPrepared = 195.0,
      quantityConsumed = 175.0,
      quantityRemaining = 20.0,
      quantityRescued = 18.0,
      quantityWasted = 2.0,
      ordersCount = 172,
      isHoliday = false,
      isWeekend = false,
      specialEvent = null,
      weatherContext = "Cloudy 26°C"
    ),
    HistoricalLogEntity(
      providerId = providerId,
      date = "2026-08-27",
      dayOfWeek = "Wednesday",
      mealType = "Lunch",
      foodItems = "Rice, Sambar, Mix Veg Curry, Chapati",
      quantityPrepared = 210.0,
      quantityConsumed = 180.0,
      quantityRemaining = 30.0,
      quantityRescued = 25.0,
      quantityWasted = 5.0,
      ordersCount = 178,
      isHoliday = false,
      isWeekend = false,
      specialEvent = null,
      weatherContext = "Clear 27°C"
    ),
    HistoricalLogEntity(
      providerId = providerId,
      date = "2026-08-28",
      dayOfWeek = "Thursday",
      mealType = "Lunch",
      foodItems = "Veg Biryani, Raita, Dal Makhani, Naan",
      quantityPrepared = 220.0,
      quantityConsumed = 185.0,
      quantityRemaining = 35.0,
      quantityRescued = 30.0,
      quantityWasted = 5.0,
      ordersCount = 182,
      isHoliday = false,
      isWeekend = false,
      specialEvent = null,
      weatherContext = "Hot 31°C"
    ),
    HistoricalLogEntity(
      providerId = providerId,
      date = "2026-08-29",
      dayOfWeek = "Friday",
      mealType = "Lunch",
      foodItems = "Rice, Rajma, Baingan Bharta, Chapati",
      quantityPrepared = 190.0,
      quantityConsumed = 168.0,
      quantityRemaining = 22.0,
      quantityRescued = 20.0,
      quantityWasted = 2.0,
      ordersCount = 164,
      isHoliday = false,
      isWeekend = false,
      specialEvent = null,
      weatherContext = "Rainy 24°C"
    )
  )
}
